version: 2
updates:
- package-ecosystem: npm
  directory: "/standalone"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  target-branch: dependabot_prs
  ignore:
  - dependency-name: typescript
    versions:
    - 4.1.3
  - dependency-name: "@types/node-fetch"
    versions:
    - 2.5.7
- package-ecosystem: npm
  directory: "/vscode"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  target-branch: dependabot_prs
  ignore:
  - dependency-name: vsce
    versions:
    - 1.83.0
    - 1.84.0
  - dependency-name: typescript
    versions:
    - 4.1.3
  - dependency-name: "@types/mocha"
    versions:
    - 8.2.0
  - dependency-name: mocha
    versions:
    - 8.2.1
